# Generated by Django 5.2.8 on 2025-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
