# Generated by Django 5.2.8 on 2025-11-25 05:10

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_projects', '0002_alter_project_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['issue', '-created_at'], name='tracking_pr_issue_i_af1447_idx'),
        ),
        migrations.AddIndex(
            model_name='contributor',
            index=models.Index(fields=['project', 'user'], name='tracking_pr_project_002034_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', '-created_at'], name='tracking_pr_project_aa18f2_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['author'], name='tracking_pr_author__4c7735_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assigned_to'], name='tracking_pr_assigne_0acca2_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='tracking_pr_status_3532fa_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['author', '-created_at'], name='tracking_pr_author__0e6c17_idx'),
        ),
    ]
