# Generated by Django 5.2.7 on 2025-11-04 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(16)]),
        ),
    ]
