# Generated by Django 5.2.8 on 2025-11-12 13:52

import authentication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[authentication.models.validate_age]),
            preserve_default=False,
        ),
    ]
