# Generated by Django 5.2.8 on 2025-11-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee',
            new_name='assigned_to',
        ),
    ]
